In [2]:
#introduction to Numpy
#use 陣列(array) to deal with 列表(list)
#處理多維度的資料
#陣列運算速度高於列表

import numpy as np
#利用列表建立 ndarray 物件
ndarr = np.array([3,4,-5])
print(ndarr) #把物件中的資料印出來
print(ndarr.size) #取得資料的數量

[ 3  4 -5]
3


In [4]:
#建立一維陣列
import numpy as np
data = np.array([3,2,6,4]) #把list轉成 numpy array
print(data)
data = np.empty(4) #創造一個有四個資料的一維陣列，但資料未指定
print(data)
data = np.zeros(3) #創造有3個資料的一維陣列，但資料全為0
print(data)
data = np.ones(3) #創造有3個資料的一維陣列，但資料全為1
print(data)
data = np.arange(5) #創造一個連續資料(共五個)的陣列
print(data)

[3 2 6 4]
[2.12199579e-314 4.67296746e-307 6.71929278e-321 3.79442416e-321]
[0. 0. 0.]
[1. 1. 1.]
[0 1 2 3 4]


In [8]:
#建立二維陣列
import numpy as np
data = np.array([
    [2,3,2],
    [1,5,2],
    [4,2,1]
]) #把list轉成 numpy array
print(data)
data = np.empty([3,3]) #創造一個3x3 的 二維陣列，但資料未指定
print(data)
data = np.zeros([2,3]) #創造 2x3 的 二維陣列，但資料全為0
print(data)
data = np.ones([3,3]) #創造 3x3 的二維陣列，但資料全為1
print(data)

[[2 3 2]
 [1 5 2]
 [4 2 1]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
#建立三維陣列
import numpy as np
data = np.array([ #根據列表創造一個 2x2x2 的三維陣列
    [
        [3,1],[1,2]
    ],
    [
        [2,5],[10,2]
    ]
]) #把list轉成 numpy array
print(data)
print()
data = np.zeros([2,2,3]) #創造 2x2x3 的 三維陣列，但資料全為0
print(data)
print()
data = np.ones([3,3,4]) #創造 3x3x4 的三維陣列，但資料全為1
print(data)
print()

[[[ 3  1]
  [ 1  2]]

 [[ 2  5]
  [10  2]]]

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]



In [33]:
#運算
# 逐元(element)運算
#note: array型態要類似
import numpy as np
data1 = np.array([3,2,10])
data2 = np.array([1,3,6])
result = data1 + data2 #加減乘除都可用
print(result)
#比較運算
result = data1 > data2 # >、 < 、 !=、 ==可用
print(result)

#矩陣運算 (matrix)
data1 = np.array([
    [1,3]
]) #1x2
data2 = np.array([
    [2,-1,3],
    [-2,4,1]
]) #2x3
result = data1.dot(data2) #1x3 (矩陣乘法)
print(result)
print()
#result = data1@data2 ，這也是矩陣乘法的寫法

result = np.outer(data1,data2) #2x6
#note: 第一個矩陣有2個元素，第二個矩陣有6個元素
#算法是 取一個元素乘上另一個所有
print(result)

#統計運算 (statistics)
data = np.array([
    [2,1,7],
    [-5,3,8]
]) # 2x3
print("總和:",data.sum())
print("最大值:",data.max())
print("平均數:",data.mean())
print("標準差:",data.std())
print("針對欄(column) 做總和:",data.sum(axis = 0))
print("針對列(row) 做總和: ",data.sum(axis = 1))
#加上axis可以針對列 或 欄 做運算
# example:
# data.max(axis = 0)
# data.mean(axis = 1)

#逐值累加 cumsum()
#一個一個照順序加起來
print("逐值累加:", data.cumsum())
print("針對欄做累加:\n",data.cumsum(axis = 0))

[ 4  5 16]
[ True False  True]
[[-4 11  6]]

[[ 2 -1  3 -2  4  1]
 [ 6 -3  9 -6 12  3]]
總和: 16
最大值: 8
平均數: 2.6666666666666665
標準差: 4.268749491621899
針對欄(column) 做總和: [-3  4 15]
針對列(row) 做總和:  [10  6]
逐值累加: [ 2  3 10  5  8 16]
針對欄做累加:
 [[ 2  1  7]
 [-3  4 15]]


In [6]:
# 扁平化資料: 把多維度的資料壓平為單維度的資料
# reshape : 重塑資料形狀
import numpy as np
# 1.觀察資料形狀
data = np.ones(10) #[1,1,1,1,1,1,1,1,1,1]
print(data.shape)
data = np.array([
    [3,1,5],
    [1,2,3]
])
print(data.shape)
print()

# 2.資料轉置 (得到轉置矩陣，列變行、行變列)
print(data.T)
print(data.T.shape)
print()

# 3.扁平化資料
data = np.array([
    [
        [2,1,3],[1,2,3]
    ],
    [
        [0,2,1],[8,9,10]
    ]
]) # shape: (2,2,3)
newdata = data.ravel() # shape: (12,) 一維的
print(newdata)
print()

# 4.重塑資料形狀
# data有12個數字，reshape時形狀個數要剛剛好
newdata =data.reshape(3,4)
print(newdata)

(10,)
(2, 3)

[[3 1]
 [1 2]
 [5 3]]
(3, 2)

[ 2  1  3  1  2  3  0  2  1  8  9 10]

[[ 2  1  3  1]
 [ 2  3  0  2]
 [ 1  8  9 10]]


In [13]:
# 多維度的索引資料 [i1,i2,....etc]
# ndarray 也有 slicing
# 多維度資料 也可以slicing [開始:結束, 開始:結束]
# 如果多維度資料slicing 用到 ...代表全部都要

import numpy as np
# 1.單維度的資料
data = np.array([1,5,2,10])
print(data[1])
print()
# 2.多維度的資料
data = np.array([
    [0,1],
    [10,-5],
    [2,6]
])
print(data[0,1]) #1
print(data[1,0]) #10
print(data[2,0]) #2
print()

# 3.單維度的slicing
data = np.array([-1, -5 , 2 ,3])
print(data[0:3])
print(data[:2])
print(data[1:])
print(data[:])
print()

# 4.多維度的slicing
data = np.array([
    [0,1,2],[3,4,5],
    [5,4,3],[2,1,0]
])
print(data[1:3]) #只取一維
print()
print(data[1:3, 0:2]) #取完一維，再取第二維
print()
print(data[0:2 , 1])
print()

# 5.使用... 代表我全都要
data = np.array([
    [
        [8,1,3],[-5,5,2]
    ],
    [
        [0,1,6],[4,4,3]
    ]
])
print(data[0, ...]) #[ [8,1,3], [-5,5,2] ]
print()
print(data[..., 1:3])

5

1
10
2

[-1 -5  2]
[-1 -5]
[-5  2  3]
[-1 -5  2  3]

[[3 4 5]
 [5 4 3]]

[[3 4]
 [5 4]]

[1 4]

[[ 8  1  3]
 [-5  5  2]]

[[[1 3]
  [5 2]]

 [[1 6]
  [4 3]]]


In [17]:
# 合併操作
# -合併第一個維度 vstack( (陣列一,陣列二, ..) )
# -合併第二個維度 hstack( (陣列一,陣列二, ..) )
# ex: 兩個1x2 :用vstack()會是(1+1)x2 ， 用hstack()會是1x(2+2)

import numpy as np
arr1 = np.array([
    [1,2,3],
    [4,5,6]
]) #2x3
arr2 = np.array([
    [7,8,9],
    [10,11,12]
]) #2x3

# 合併第一個維度
result1 = np.vstack( (arr1,arr2) )
print(result1) #4x3 = (2+2)x3
print()

# 合併第二個維度
result2 = np.hstack( (arr1,arr2) ) # 2x6 = 2x(3+3)
print(result2)
print()

# bonus: (合併第三個陣列+ 第二個維度數字不同)
arr3 = np.array([
    [13,14],
    [15,16]
])
result3 = np.hstack( (arr1,arr2) ) # 2x8 = 2x(3+3+2)
print(result3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [23]:
# 切割操作
# -切割第一個維度 vsplit( 陣列,切割數量  )
# -切割第二個維度 hsplit( 陣列,切割數量 )
# ex: 一個2x4 :用vsplit()會是兩個1x4 ， 用hsplit()會是兩個2x2

import numpy as np
arr = np.array([
    [2,4,6,8,10,12],
    [1,3,5,7,9,11]
]) #2x6

# 切割第一個維度
result1 = np.vsplit(arr,2)
print(result1)
print()

# 切割第二個維度
result2 = np.hsplit(arr,2)
print(result2)
print()

# 切割第二個維度 3份
result3 = np.hsplit(arr,3)
print(result3)
print()

[array([[ 2,  4,  6,  8, 10, 12]]), array([[ 1,  3,  5,  7,  9, 11]])]

[array([[2, 4, 6],
       [1, 3, 5]]), array([[ 8, 10, 12],
       [ 7,  9, 11]])]

[array([[2, 4],
       [1, 3]]), array([[6, 8],
       [5, 7]]), array([[10, 12],
       [ 9, 11]])]

